/* TABLA EXPEJU */
export const SET_PAGINA_EXPEJU = 'SET_PAGINA_EXPEJU'
export const SET_REGISTRO_ACTUAL_EXPEJU = 'SET_REGISTRO_ACTUAL_EXPEJU'
export const SET_FILTRO_EXPEJU = 'SET_FILTRO_EXPEJU'
export const SET_CAMPOS_FILTRO_EXPEJU = 'SET_CAMPOS_FILTRO_EXPEJU'
export const SET_ORDENACION_EXPEJU = 'SET_ORDENACION_EXPEJU'

/* TABLA EXJUTE */
export const SET_PAGINA_EXJUTE = 'SET_PAGINA_EXJUTE'
export const SET_REGISTRO_ACTUAL_EXJUTE = 'SET_REGISTRO_ACTUAL_EXJUTE'
export const SET_FILTRO_EXJUTE = 'SET_FILTRO_EXJUTE'
export const SET_CAMPOS_FILTRO_EXJUTE = 'SET_CAMPOS_FILTRO_EXJUTE'
export const SET_ORDENACION_EXJUTE = 'SET_ORDENACION_EXJUTE'

/* TABLA EXJUAB */
export const SET_PAGINA_EXJUAB = 'SET_PAGINA_EXJUAB'
export const SET_REGISTRO_ACTUAL_EXJUAB = 'SET_REGISTRO_ACTUAL_EXJUAB'
export const SET_FILTRO_EXJUAB = 'SET_FILTRO_EXJUAB'
export const SET_CAMPOS_FILTRO_EXJUAB = 'SET_CAMPOS_FILTRO_EXJUAB'
export const SET_ORDENACION_EXJUAB = 'SET_ORDENACION_EXJUAB'

/* TABLA EXJURE */
export const SET_PAGINA_EXJURE = 'SET_PAGINA_EXJURE'
export const SET_REGISTRO_ACTUAL_EXJURE = 'SET_REGISTRO_ACTUAL_EXJURE'
export const SET_FILTRO_EXJURE = 'SET_FILTRO_EXJURE'
export const SET_CAMPOS_FILTRO_EXJURE = 'SET_CAMPOS_FILTRO_EXJURE'
export const SET_ORDENACION_EXJURE = 'SET_ORDENACION_EXJURE'
