/* TABLA CONSULTA EXISTE ADAPTADA A MULTIMEDIA */
export const SET_PAGINA_CONSULTA_MM = 'SET_PAGINA_CONSULTA_MM'
export const SET_REGISTRO_ACTUAL_CONSULTA_MM = 'SET_REGISTRO_ACTUAL_CONSULTA_MM'
export const SET_FILTRO_CONSULTA_MM = 'SET_FILTRO_CONSULTA_MM'
export const SET_CAMPOS_FILTRO_CONSULTA_MM = 'SET_CAMPOS_FILTRO_CONSULTA_MM'
export const SET_ORDENACION_CONSULTA_MM = 'SET_ORDENACION_CONSULTA_MM'
