/* TABLA OBRAS */
export const SET_PAGINA_OBRAS = 'SET_PAGINA_OBRAS'
export const SET_REGISTRO_ACTUAL_OBRAS = 'SET_REGISTRO_ACTUAL_OBRAS'
export const SET_FILTRO_OBRAS = 'SET_FILTRO_OBRAS'
export const SET_CAMPOS_FILTRO_OBRAS = 'SET_CAMPOS_FILTRO_OBRAS'
export const SET_ORDENACION_OBRAS = 'SET_ORDENACION_OBRAS'
